# Generated by Django 5.1.6 on 2025-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='writer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
